# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"!\n\x04\x43hat\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"*\n\x0b\x43hatMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"@\n\x12GetAllChatsRequest\x12\x19\n\x0c\x66ilter_by_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0f\n\r_filter_by_id\"0\n\x13GetAllChatsResponse\x12\x19\n\x05\x63hats\x18\x01 \x03(\x0b\x32\n.chat.Chat\"\x1c\n\x0eGetChatRequest\x12\n\n\x02id\x18\x01 \x01(\t\"A\n\x0fGetChatResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\"\n\x07message\x18\x02 \x03(\x0b\x32\x11.chat.ChatMessage\"-\n\x11\x43reateChatRequest\x12\x18\n\x04\x63hat\x18\x01 \x01(\x0b\x32\n.chat.Chat\".\n\x12\x43reateChatResponse\x12\x18\n\x04\x63hat\x18\x01 \x01(\x0b\x32\n.chat.Chat\"\x1f\n\x11\x44\x65leteChatRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x14\n\x12\x44\x65leteChatResponse\"P\n\x16SendChatMessageRequest\x12\x0f\n\x07\x63hat_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x61llback_url\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"*\n\x17SendChatMessageResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xf5\x01\n\x0b\x43hatService\x12\x41\n\nDeleteChat\x12\x17.chat.DeleteChatRequest\x1a\x18.chat.DeleteChatResponse\"\x00\x12P\n\x0fSendChatMessage\x12\x1c.chat.SendChatMessageRequest\x1a\x1d.chat.SendChatMessageResponse\"\x00\x12Q\n\x10SendChainMessage\x12\x1c.chat.SendChatMessageRequest\x1a\x1d.chat.SendChatMessageResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHAT._serialized_start=20
  _CHAT._serialized_end=53
  _CHATMESSAGE._serialized_start=55
  _CHATMESSAGE._serialized_end=97
  _GETALLCHATSREQUEST._serialized_start=99
  _GETALLCHATSREQUEST._serialized_end=163
  _GETALLCHATSRESPONSE._serialized_start=165
  _GETALLCHATSRESPONSE._serialized_end=213
  _GETCHATREQUEST._serialized_start=215
  _GETCHATREQUEST._serialized_end=243
  _GETCHATRESPONSE._serialized_start=245
  _GETCHATRESPONSE._serialized_end=310
  _CREATECHATREQUEST._serialized_start=312
  _CREATECHATREQUEST._serialized_end=357
  _CREATECHATRESPONSE._serialized_start=359
  _CREATECHATRESPONSE._serialized_end=405
  _DELETECHATREQUEST._serialized_start=407
  _DELETECHATREQUEST._serialized_end=438
  _DELETECHATRESPONSE._serialized_start=440
  _DELETECHATRESPONSE._serialized_end=460
  _SENDCHATMESSAGEREQUEST._serialized_start=462
  _SENDCHATMESSAGEREQUEST._serialized_end=542
  _SENDCHATMESSAGERESPONSE._serialized_start=544
  _SENDCHATMESSAGERESPONSE._serialized_end=586
  _CHATSERVICE._serialized_start=589
  _CHATSERVICE._serialized_end=834
# @@protoc_insertion_point(module_scope)
