# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import chat_pb2 as chat__pb2


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeleteChat = channel.unary_unary(
                '/chat.ChatService/DeleteChat',
                request_serializer=chat__pb2.DeleteChatRequest.SerializeToString,
                response_deserializer=chat__pb2.DeleteChatResponse.FromString,
                )
        self.SendChatMessage = channel.unary_unary(
                '/chat.ChatService/SendChatMessage',
                request_serializer=chat__pb2.SendChatMessageRequest.SerializeToString,
                response_deserializer=chat__pb2.SendChatMessageResponse.FromString,
                )
        self.SendChainMessage = channel.unary_unary(
                '/chat.ChatService/SendChainMessage',
                request_serializer=chat__pb2.SendChatMessageRequest.SerializeToString,
                response_deserializer=chat__pb2.SendChatMessageResponse.FromString,
                )


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeleteChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendChatMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendChainMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeleteChat': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChat,
                    request_deserializer=chat__pb2.DeleteChatRequest.FromString,
                    response_serializer=chat__pb2.DeleteChatResponse.SerializeToString,
            ),
            'SendChatMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendChatMessage,
                    request_deserializer=chat__pb2.SendChatMessageRequest.FromString,
                    response_serializer=chat__pb2.SendChatMessageResponse.SerializeToString,
            ),
            'SendChainMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendChainMessage,
                    request_deserializer=chat__pb2.SendChatMessageRequest.FromString,
                    response_serializer=chat__pb2.SendChatMessageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeleteChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/DeleteChat',
            chat__pb2.DeleteChatRequest.SerializeToString,
            chat__pb2.DeleteChatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendChatMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/SendChatMessage',
            chat__pb2.SendChatMessageRequest.SerializeToString,
            chat__pb2.SendChatMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendChainMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chat.ChatService/SendChainMessage',
            chat__pb2.SendChatMessageRequest.SerializeToString,
            chat__pb2.SendChatMessageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
